services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  socket-server:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./socket-server:/app
    command: sh -c "npm install && node index.js"
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

