ALTER TABLE teacher_assignments ADD CONSTRAINT FK_E6D6EC9741807E1D FOREIGN KEY (teacher_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE users CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE role_id role_id INT DEFAULT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE first_name first_name VARCHAR(255) NOT NULL, CHANGE last_name last_name VARCHAR(255) NOT NULL, CHANGE gender gender VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE employee_id employee_id VARCHAR(255) DEFAULT NULL, CHANGE student_id student_id VARCHAR(255) DEFAULT NULL, CHANGE is_active is_active TINYINT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL;
ALTER TABLE users RENAME INDEX idx_users_role TO IDX_1483A5E9D60322AC;
ALTER TABLE message_reads DROP FOREIGN KEY `message_reads_ibfk_1`;
ALTER TABLE message_reads DROP FOREIGN KEY `message_reads_ibfk_2`;
DROP INDEX message_id ON message_reads;
ALTER TABLE message_reads MODIFY id BIGINT NOT NULL;
ALTER TABLE message_reads DROP id, DROP read_at, CHANGE message_id message_id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (user_id, message_id);
ALTER TABLE message_reads ADD CONSTRAINT FK_37E6935AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE message_reads ADD CONSTRAINT FK_37E6935A537A1329 FOREIGN KEY (message_id) REFERENCES messages (id);
ALTER TABLE message_reads RENAME INDEX user_id TO IDX_37E6935AA76ED395;
ALTER TABLE student_enrollments DROP INDEX class_id, ADD INDEX IDX_1B38CC31EA000B10 (class_id);
ALTER TABLE student_enrollments DROP FOREIGN KEY `student_enrollments_ibfk_2`;
DROP INDEX idx_enrollments_filters ON student_enrollments;
ALTER TABLE student_enrollments CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE class_id class_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL;
ALTER TABLE student_enrollments ADD CONSTRAINT FK_1B38CC31A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE student_enrollments RENAME INDEX idx_enrollment_active TO IDX_1B38CC31A76ED395;
ALTER TABLE student_enrollments RENAME INDEX fk_1b38cc31c54f3401 TO IDX_1B38CC31C54F3401;
ALTER TABLE chapter_progress DROP INDEX student_id, ADD UNIQUE INDEX UNIQ_C4189F43CB944F1A (student_id);
ALTER TABLE chapter_progress DROP INDEX IDX_C4189F43579F4768, ADD UNIQUE INDEX UNIQ_C4189F43579F4768 (chapter_id);
ALTER TABLE chapter_progress DROP FOREIGN KEY `chapter_progress_ibfk_1`;
ALTER TABLE chapter_progress DROP FOREIGN KEY `chapter_progress_ibfk_2`;
DROP INDEX chapter_id ON chapter_progress;
ALTER TABLE chapter_progress CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE chapter_id chapter_id INT DEFAULT NULL, CHANGE student_id student_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE last_accessed_at last_accessed_at DATETIME DEFAULT NULL;
ALTER TABLE chapter_progress ADD CONSTRAINT FK_C4189F43579F4768 FOREIGN KEY (chapter_id) REFERENCES chapters (id);
ALTER TABLE chapter_progress ADD CONSTRAINT FK_C4189F43CB944F1A FOREIGN KEY (student_id) REFERENCES users (id);
ALTER TABLE forum_post_attachments DROP FOREIGN KEY `forum_post_attachments_ibfk_1`;
ALTER TABLE forum_post_attachments CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE post_id post_id INT DEFAULT NULL, CHANGE file_type file_type VARCHAR(255) DEFAULT NULL, CHANGE uploaded_at uploaded_at DATETIME DEFAULT NULL;
ALTER TABLE forum_post_attachments ADD CONSTRAINT FK_2BB74F104B89032C FOREIGN KEY (post_id) REFERENCES forum_posts (id);
ALTER TABLE forum_post_attachments RENAME INDEX post_id TO IDX_2BB74F104B89032C;
ALTER TABLE forum_posts DROP FOREIGN KEY `fk_fw_posts_user`;
ALTER TABLE forum_posts CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE class_id class_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE content content LONGTEXT NOT NULL, CHANGE created_by created_by INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL;
ALTER TABLE forum_posts ADD CONSTRAINT FK_90291C2DDE12AB56 FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE forum_posts RENAME INDEX idx_fw_posts_class TO IDX_90291C2DEA000B10;
ALTER TABLE forum_posts RENAME INDEX idx_fw_posts_user TO IDX_90291C2DDE12AB56;
DROP INDEX idx_classes_selector ON classes;
ALTER TABLE classes CHANGE name name VARCHAR(255) NOT NULL, CHANGE grade_level grade_level VARCHAR(255) NOT NULL, CHANGE section section VARCHAR(255) DEFAULT NULL, CHANGE is_active is_active TINYINT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL;
ALTER TABLE conversations DROP FOREIGN KEY `conversations_ibfk_1`;
DROP INDEX pair_hash ON conversations;
ALTER TABLE conversations CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE pair_hash pair_hash VARCHAR(255) DEFAULT NULL, CHANGE created_by created_by INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL;
ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE conversations RENAME INDEX created_by TO IDX_C2521BF1DE12AB56;
DROP INDEX idx_subjects_selector_v2 ON subjects;
DROP INDEX subject_code ON subjects;
ALTER TABLE subjects ADD term_id INT DEFAULT NULL, CHANGE subject_code subject_code VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE is_active is_active TINYINT DEFAULT NULL;
ALTER TABLE subjects ADD CONSTRAINT FK_AB259917E2C35FC FOREIGN KEY (term_id) REFERENCES terms (id);
CREATE INDEX IDX_AB259917E2C35FC ON subjects (term_id);
ALTER TABLE chapter_contents DROP FOREIGN KEY `chapter_contents_ibfk_1`;
ALTER TABLE chapter_contents DROP FOREIGN KEY `chapter_contents_ibfk_2`;
ALTER TABLE chapter_contents CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE item_id item_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE created_by created_by INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
ALTER TABLE chapter_contents ADD CONSTRAINT FK_52E37C72126F525E FOREIGN KEY (item_id) REFERENCES chapter_items (id);
ALTER TABLE chapter_contents ADD CONSTRAINT FK_52E37C72DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE chapter_contents RENAME INDEX item_id TO UNIQ_52E37C72126F525E;
ALTER TABLE chapter_contents RENAME INDEX created_by TO IDX_52E37C72DE12AB56;
ALTER TABLE assignments DROP FOREIGN KEY `assignments_ibfk_1`;
DROP INDEX idx_assignments_chapter ON assignments;
ALTER TABLE assignments CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE chapter_id chapter_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE submission_type submission_type VARCHAR(255) DEFAULT NULL, CHANGE allow_late_submission allow_late_submission TINYINT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE type type VARCHAR(255) NOT NULL;
ALTER TABLE assignments ADD CONSTRAINT FK_308A50DD579F4768 FOREIGN KEY (chapter_id) REFERENCES chapters (id);
DROP INDEX name ON roles;
ALTER TABLE roles CHANGE name name VARCHAR(255) NOT NULL, CHANGE role_category role_category VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL;
ALTER TABLE conversation_members DROP INDEX idx_members_user, ADD UNIQUE INDEX UNIQ_DEF6DCF5A76ED395 (user_id);
ALTER TABLE conversation_members DROP INDEX IDX_DEF6DCF59AC0396, ADD UNIQUE INDEX UNIQ_DEF6DCF59AC0396 (conversation_id);
ALTER TABLE conversation_members DROP FOREIGN KEY `conversation_members_ibfk_1`;
ALTER TABLE conversation_members DROP FOREIGN KEY `conversation_members_ibfk_2`;
DROP INDEX conversation_id ON conversation_members;
ALTER TABLE conversation_members CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE conversation_id conversation_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE role role VARCHAR(255) DEFAULT NULL, CHANGE joined_at joined_at DATETIME DEFAULT NULL;
ALTER TABLE conversation_members ADD CONSTRAINT FK_DEF6DCF59AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id);
ALTER TABLE conversation_members ADD CONSTRAINT FK_DEF6DCF5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE chapter_files DROP FOREIGN KEY `chapter_files_ibfk_1`;
ALTER TABLE chapter_files DROP FOREIGN KEY `chapter_files_ibfk_2`;
ALTER TABLE chapter_files CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE item_id item_id INT DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) NOT NULL, CHANGE file_type file_type VARCHAR(255) DEFAULT NULL, CHANGE uploaded_by uploaded_by INT DEFAULT NULL, CHANGE uploaded_at uploaded_at DATETIME DEFAULT NULL;
ALTER TABLE chapter_files ADD CONSTRAINT FK_867CD6E6126F525E FOREIGN KEY (item_id) REFERENCES chapter_items (id);
ALTER TABLE chapter_files ADD CONSTRAINT FK_867CD6E6E3E73126 FOREIGN KEY (uploaded_by) REFERENCES users (id);
ALTER TABLE chapter_files RENAME INDEX item_id TO UNIQ_867CD6E6126F525E;
ALTER TABLE chapter_files RENAME INDEX uploaded_by TO IDX_867CD6E6E3E73126;
DROP INDEX idx_terms_selector ON terms;
DROP INDEX uniq_terms_current_in_year ON terms;
ALTER TABLE terms DROP current_in_year_flag, CHANGE academic_year_id academic_year_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE is_current is_current TINYINT DEFAULT NULL;
ALTER TABLE terms RENAME INDEX academic_year_id TO IDX_88A23F71C54F3401;
ALTER TABLE forum_reviews DROP INDEX idx_fw_reviews_post, ADD UNIQUE INDEX UNIQ_98BCA67E4B89032C (post_id);
ALTER TABLE forum_reviews DROP INDEX idx_fw_reviews_user, ADD UNIQUE INDEX UNIQ_98BCA67ECB944F1A (student_id);
ALTER TABLE forum_reviews DROP FOREIGN KEY `fk_fw_reviews_post`;
ALTER TABLE forum_reviews DROP FOREIGN KEY `fk_fw_reviews_user`;
DROP INDEX sync_uuid ON forum_reviews;
DROP INDEX uq_fw_review_unique ON forum_reviews;
ALTER TABLE forum_reviews CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE post_id post_id INT DEFAULT NULL, CHANGE student_id student_id INT DEFAULT NULL, CHANGE review_text review_text LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE sync_uuid sync_uuid VARCHAR(255) DEFAULT NULL;
ALTER TABLE forum_reviews ADD CONSTRAINT FK_98BCA67E4B89032C FOREIGN KEY (post_id) REFERENCES forum_posts (id);
ALTER TABLE forum_reviews ADD CONSTRAINT FK_98BCA67ECB944F1A FOREIGN KEY (student_id) REFERENCES users (id);
ALTER TABLE chapter_items DROP FOREIGN KEY `chapter_items_ibfk_1`;
DROP INDEX idx_items_chapter ON chapter_items;
ALTER TABLE chapter_items CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE chapter_id chapter_id INT DEFAULT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE sort_order sort_order INT DEFAULT NULL;
ALTER TABLE chapter_items ADD CONSTRAINT FK_61577FF2579F4768 FOREIGN KEY (chapter_id) REFERENCES chapters (id);
ALTER TABLE submissions DROP INDEX IDX_3F6169F7D19302F8, ADD UNIQUE INDEX UNIQ_3F6169F7D19302F8 (assignment_id);
ALTER TABLE submissions DROP FOREIGN KEY `submissions_ibfk_1`;
ALTER TABLE submissions DROP FOREIGN KEY `submissions_ibfk_2`;
ALTER TABLE submissions DROP FOREIGN KEY `submissions_ibfk_3`;
DROP INDEX assignment_id ON submissions;
ALTER TABLE submissions CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE assignment_id assignment_id INT DEFAULT NULL, CHANGE student_id student_id INT DEFAULT NULL, CHANGE submission_text submission_text LONGTEXT DEFAULT NULL, CHANGE is_late is_late TINYINT DEFAULT NULL, CHANGE feedback feedback LONGTEXT DEFAULT NULL, CHANGE reviewed_by reviewed_by INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
ALTER TABLE submissions ADD CONSTRAINT FK_3F6169F7D19302F8 FOREIGN KEY (assignment_id) REFERENCES assignments (id);
ALTER TABLE submissions ADD CONSTRAINT FK_3F6169F7CB944F1A FOREIGN KEY (student_id) REFERENCES users (id);
ALTER TABLE submissions ADD CONSTRAINT FK_3F6169F785D7FB47 FOREIGN KEY (reviewed_by) REFERENCES users (id);
ALTER TABLE submissions RENAME INDEX idx_submissions_student TO IDX_3F6169F7CB944F1A;
ALTER TABLE submissions RENAME INDEX reviewed_by TO IDX_3F6169F785D7FB47;
ALTER TABLE forum_comments DROP FOREIGN KEY `fk_fw_comments_parent`;
ALTER TABLE forum_comments DROP FOREIGN KEY `fk_fw_comments_post`;
ALTER TABLE forum_comments DROP FOREIGN KEY `fk_fw_comments_user`;
DROP INDEX sync_uuid ON forum_comments;
ALTER TABLE forum_comments CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE post_id post_id INT DEFAULT NULL, CHANGE parent_id parent_id INT DEFAULT NULL, CHANGE student_id student_id INT DEFAULT NULL, CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE sync_uuid sync_uuid VARCHAR(255) DEFAULT NULL;
ALTER TABLE forum_comments ADD CONSTRAINT FK_786D1BCD4B89032C FOREIGN KEY (post_id) REFERENCES forum_posts (id);
ALTER TABLE forum_comments ADD CONSTRAINT FK_786D1BCD727ACA70 FOREIGN KEY (parent_id) REFERENCES forum_comments (id);
ALTER TABLE forum_comments ADD CONSTRAINT FK_786D1BCDCB944F1A FOREIGN KEY (student_id) REFERENCES users (id);
ALTER TABLE forum_comments RENAME INDEX idx_fw_comments_post TO IDX_786D1BCD4B89032C;
ALTER TABLE forum_comments RENAME INDEX fk_fw_comments_parent TO IDX_786D1BCD727ACA70;
ALTER TABLE forum_comments RENAME INDEX idx_fw_comments_user TO IDX_786D1BCDCB944F1A;
ALTER TABLE announcements ADD CONSTRAINT FK_F422A9DAE36D154 FOREIGN KEY (posted_by) REFERENCES users (id);
ALTER TABLE announcements RENAME INDEX posted_by TO IDX_F422A9DAE36D154;
ALTER TABLE chapters DROP FOREIGN KEY `fk_chapters_subject`;
DROP INDEX idx_chapters_class_subject ON chapters;
ALTER TABLE chapters CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE sort_order sort_order INT DEFAULT NULL, CHANGE is_published is_published TINYINT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
ALTER TABLE chapters ADD CONSTRAINT FK_C721437123EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id);
ALTER TABLE chapters RENAME INDEX fk_chapters_subject TO IDX_C721437123EDC87;
ALTER TABLE messages DROP FOREIGN KEY `messages_ibfk_1`;
ALTER TABLE messages DROP FOREIGN KEY `messages_ibfk_2`;
DROP INDEX idx_messages_conversation ON messages;
ALTER TABLE messages CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE conversation_id conversation_id INT DEFAULT NULL, CHANGE sender_id sender_id INT DEFAULT NULL, CHANGE content content LONGTEXT NOT NULL, CHANGE is_deleted is_deleted TINYINT DEFAULT NULL, CHANGE sent_at sent_at DATETIME DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL;
ALTER TABLE messages ADD CONSTRAINT FK_DB021E969AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id);
ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES users (id);
ALTER TABLE messages RENAME INDEX sender_id TO IDX_DB021E96F624B39D;
ALTER TABLE submission_files DROP FOREIGN KEY `submission_files_ibfk_1`;
ALTER TABLE submission_files DROP FOREIGN KEY `submission_files_ibfk_2`;
ALTER TABLE submission_files CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE submission_id submission_id INT DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) NOT NULL, CHANGE file_type file_type VARCHAR(255) DEFAULT NULL, CHANGE uploaded_by uploaded_by INT DEFAULT NULL, CHANGE uploaded_at uploaded_at DATETIME DEFAULT NULL;
ALTER TABLE submission_files ADD CONSTRAINT FK_DBAA3AFBE1FD4933 FOREIGN KEY (submission_id) REFERENCES submissions (id);
ALTER TABLE submission_files ADD CONSTRAINT FK_DBAA3AFBE3E73126 FOREIGN KEY (uploaded_by) REFERENCES users (id);
ALTER TABLE submission_files RENAME INDEX submission_id TO IDX_DBAA3AFBE1FD4933;
ALTER TABLE submission_files RENAME INDEX uploaded_by TO IDX_DBAA3AFBE3E73126;
